'''
************************************************  mistralai/mistral-7b-instruct-v0.3   ************************************************
from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
import json

# 1.LLM CONFIGURATION (LM Studio - NO API KEY)

llm = ChatOpenAI(
    base_url="http://localhost:1234/v1",  
    api_key="lm-studio",                  
    model="local-model",                  
    temperature=0
)

# 2. STATE DEFINITION

class InstructionState(TypedDict):
    input: str
    output: dict

# 3. PARSER NODE

def parse_instruction(state: InstructionState) -> InstructionState:
    prompt = f"""
You are an AI test case parser.

Convert the following natural language test case into STRICT JSON.
Do NOT add explanations.

JSON format:
{{
  "action": "<short action name>",
  "steps": ["step1", "step2", "..."],
  "assertions": ["assertion1", "assertion2"]
}}

Test case:
{state["input"]}
"""

    response = llm.invoke(prompt)

    # Ensure valid JSON output
    try:
        parsed = json.loads(response.content)
    except json.JSONDecodeError:
        parsed = {
            "error": "Invalid JSON generated by model",
            "raw_output": response.content
        }

    return {
        "input": state["input"],
        "output": parsed
    }

# 4. LANGGRAPH SETUP

graph = StateGraph(InstructionState)
graph.add_node("instruction_parser", parse_instruction)
graph.set_entry_point("instruction_parser")
graph.add_edge("instruction_parser", END)

instruction_parser = graph.compile()

if __name__ == "__main__":
    print("=== Instruction Parser (LM Studio, No API Key) ===\n")
    test_case = input("Enter test case: ")

    result = instruction_parser.invoke({
        "input": test_case
    })

    print("\nParsed Output:")
    print(json.dumps(result["output"], indent=2))'''

#*******************************************************  models/gemini-flash-latest   *******************************************************
from typing import TypedDict
import json
import re

from google import genai
from langgraph.graph import StateGraph, END
client = genai.Client(
    api_key=""
)

#list available models
'''available_models = client.models.list()
print("Available models for generate_content:")
for model in available_models:
    print(model.name)'''

MODEL_NAME = "models/gemini-flash-latest"
class ParserState(TypedDict):
    input: str
    output: dict

SYSTEM_PROMPT = """
Convert the given test case into STRICT JSON.

Rules:
- Output ONLY valid JSON
- No explanations
- Fields:
  - action (string)
  - steps (array of strings)
  - assertions (array of strings)
"""
def parse_instruction(state: ParserState) -> ParserState:
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=f"{SYSTEM_PROMPT}\n\nTest case:\n{state['input']}",
        config={
            "temperature": 0,
            "max_output_tokens": 1024
        }
    )

    text = response.text.strip()

    # Remove markdown if present
    text = re.sub(r"^```(json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    # Extract JSON object
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"Invalid JSON generated: {text}")

    parsed = json.loads(match.group())

    return {
        "input": state["input"],
        "output": parsed
    }

def validate_json(state: ParserState) -> ParserState:
    required = {"action", "steps", "assertions"}
    if not required.issubset(state["output"].keys()):
        raise ValueError(f"Missing required JSON fields: {state['output'].keys()}")

    return state

graph = StateGraph(ParserState)

graph.add_node("parse_instruction", parse_instruction)
graph.add_node("validate_json", validate_json)

graph.set_entry_point("parse_instruction")
graph.add_edge("parse_instruction", "validate_json")
graph.add_edge("validate_json", END)

agent = graph.compile()


if __name__ == "__main__":
    print("LangGraph Instruction Parser (Gemini)")
    print("-" * 50)

    test_case = input("Enter test case: ")

    try:
        result = agent.invoke({"input": test_case})
        print("\nParsed JSON Output:")
        print(json.dumps(result["output"], indent=2))
    except Exception as e:
        print(f"\n Error: {e}")



'''
test cases:
Navigate to login page, enter valid username and invalid password, click login and verify an error message is shown
Open the login page, enter valid username and password, click login and verify the dashboard is displayed
Open the login page, click login without entering credentials and verify validation messages appear
Open the signup page, enter valid user details, submit the form and verify account is created successfully
Enter a valid product name in the search bar, click search and verify relevant results are displayed
'''